In [10]:
from pathlib import Path
import pandas as pd

BASE_DIR = Path.cwd().parent
DATASET = BASE_DIR / "datasets" / "marketing_campaign.csv"

df = pd.read_csv(DATASET, sep="\t")

In [11]:
df.isna().sum()

ID                      0
Year_Birth              0
Education               0
Marital_Status          0
Income                 24
Kidhome                 0
Teenhome                0
Dt_Customer             0
Recency                 0
MntWines                0
MntFruits               0
MntMeatProducts         0
MntFishProducts         0
MntSweetProducts        0
MntGoldProds            0
NumDealsPurchases       0
NumWebPurchases         0
NumCatalogPurchases     0
NumStorePurchases       0
NumWebVisitsMonth       0
AcceptedCmp3            0
AcceptedCmp4            0
AcceptedCmp5            0
AcceptedCmp1            0
AcceptedCmp2            0
Complain                0
Z_CostContact           0
Z_Revenue               0
Response                0
dtype: int64

In [12]:
df[df["Income"].isna()]

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,NumWebVisitsMonth,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Z_CostContact,Z_Revenue,Response
10,1994,1983,Graduation,Married,NaN,1,0,15-11-2013,11,5,...,7,0,0,0,0,0,0,3,11,0
27,5255,1986,Graduation,Single,NaN,1,0,20-02-2013,19,5,...,1,0,0,0,0,0,0,3,11,0
43,7281,1959,PhD,Single,NaN,0,0,05-11-2013,80,81,...,2,0,0,0,0,0,0,3,11,0
48,7244,1951,Graduation,Single,NaN,2,1,01-01-2014,96,48,...,6,0,0,0,0,0,0,3,11,0
58,8557,1982,Graduation,Single,NaN,1,0,17-06-2013,57,11,...,6,0,0,0,0,0,0,3,11,0
71,10629,1973,2n Cycle,Married,NaN,1,0,14-09-2012,25,25,...,8,0,0,0,0,0,0,3,11,0
90,8996,1957,PhD,Married,NaN,2,1,19-11-2012,4,230,...,9,0,0,0,0,0,0,3,11,0
91,9235,1957,Graduation,Single,NaN,1,1,27-05-2014,45,7,...,7,0,0,0,0,0,0,3,11,0
92,5798,1973,Master,Together,NaN,0,0,23-11-2013,87,445,...,1,0,0,0,0,0,0,3,11,0
128,8268,1961,PhD,Married,NaN,0,1,11-07-2013,23,352,...,6,0,0,0,0,0,0,3,11,0
133,1295,1963,Graduation,Married,NaN,0,1,11-08-2013,96,231,...,4,0,0,0,0,0,0,3,11,0
312,2437,1989,Graduation,Married,NaN,0,0,03-06-2013,69,861,...,3,0,1,0,1,0,0,3,11,0
319,2863,1970,Graduation,Single,NaN,1,2,23-08-2013,67,738,...,7,0,1,0,1,0,0,3,11,0
1379,10475,1970,Master,Together,NaN,0,1,01-04-2013,39,187,...,5,0,0,0,0,0,0,3,11,0
1382,2902,1958,Graduation,Together,NaN,1,1,03-09-2012,87,19,...,5,0,0,0,0,0,0,3,11,0
1383,4345,1964,2n Cycle,Single,NaN,1,1,12-01-2014,49,5,...,7,0,0,0,0,0,0,3,11,0
1386,3769,1972,PhD,Together,NaN,1,0,02-03-2014,17,25,...,7,0,0,0,0,0,0,3,11,0
2059,7187,1969,Master,Together,NaN,1,1,18-05-2013,52,375,...,3,0,0,0,0,0,0,3,11,0
2061,1612,1981,PhD,Single,NaN,1,0,31-05-2013,82,23,...,6,0,0,0,0,0,0,3,11,0
2078,5079,1971,Graduation,Married,NaN,1,1,03-03-2013,82,71,...,8,0,0,0,0,0,0,3,11,0
2079,10339,1954,Master,Together,NaN,0,1,23-06-2013,83,161,...,6,0,0,0,0,0,0,3,11,0
2081,3117,1955,Graduation,Single,NaN,0,1,18-10-2013,95,264,...,7,0,0,0,0,0,0,3,11,0
2084,5250,1943,Master,Widow,NaN,0,0,30-10-2013,75,532,...,1,0,0,1,0,0,0,3,11,1
2228,8720,1978,2n Cycle,Together,NaN,0,0,12-08-2012,53,32,...,0,0,1,0,0,0,0,3,11,0

In [13]:
clean_df = df.dropna(subset=["Income"])
clean_df.shape

(2216, 29)

In [14]:
mean = df["Income"].mean()
filled_df = df.copy()
filled_df["Income"] = filled_df["Income"].fillna(mean)
filled_df.isna().sum()

ID                     0
Year_Birth             0
Education              0
Marital_Status         0
Income                 0
Kidhome                0
Teenhome               0
Dt_Customer            0
Recency                0
MntWines               0
MntFruits              0
MntMeatProducts        0
MntFishProducts        0
MntSweetProducts       0
MntGoldProds           0
NumDealsPurchases      0
NumWebPurchases        0
NumCatalogPurchases    0
NumStorePurchases      0
NumWebVisitsMonth      0
AcceptedCmp3           0
AcceptedCmp4           0
AcceptedCmp5           0
AcceptedCmp1           0
AcceptedCmp2           0
Complain               0
Z_CostContact          0
Z_Revenue              0
Response               0
dtype: int64

In [52]:
df["Dt_Customer"] = pd.to_datetime(df["Dt_Customer"], format="%d-%m-%Y")
df["Dt_Customer"].dtypes
df["Dt_Customer"].dt.month.head()
df["Dt_Customer"].dt.year.head()
df["Dt_Customer"].dt.day_name().value_counts()
df["Customer_Year"] = df["Dt_Customer"].dt.year
df["Customer_Month"] = df["Dt_Customer"].dt.month
df["Customer_Day"] = df["Dt_Customer"].dt.day

df[[
    "Dt_Customer",
    "Customer_Year",
    "Customer_Month",
    "Customer_Day"
]].head()

df[df["Dt_Customer"].dt.year == 2014].shape[0]

df["Income"] = pd.to_numeric(df["Income"])
df["Income"].dtype

clean_data = pd.to_numeric(
    df["Income"],
    errors="coerce"
)
df["Income"] = clean_data

#finding suspicious birth years
df["Year_Birth"].value_counts().sort_index().head(10)
df[df["Year_Birth"] < 1900]

df[df["Income"] < 0]

Empty DataFrame
Columns: [ID, Year_Birth, Education, Marital_Status, Income, Kidhome, Teenhome, Dt_Customer, Recency, MntWines, MntFruits, MntMeatProducts, MntFishProducts, MntSweetProducts, MntGoldProds, NumDealsPurchases, NumWebPurchases, NumCatalogPurchases, NumStorePurchases, NumWebVisitsMonth, AcceptedCmp3, AcceptedCmp4, AcceptedCmp5, AcceptedCmp1, AcceptedCmp2, Complain, Z_CostContact, Z_Revenue, Response, Customer_Year, Customer_Month, Customer_Day]
Index: []

[0 rows x 32 columns]